# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-22 01:41
from __future__ import unicode_literals

import autoslug.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('name', models.TextField(max_length=100, primary_key=True, serialize=False)),
                ('genre', models.TextField(max_length=100)),
                ('slug', autoslug.fields.AutoSlugField(max_length=30)),
                ('image', models.ImageField(upload_to='group_photos')),
            ],
        ),
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=5000)),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
    ]
