# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-22 02:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('songs', '0002_song_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='slug',
        ),
        migrations.AlterField(
            model_name='song',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='songs.Group'),
        ),
    ]
